export const LOAD_SCHOOLS = 'LOAD_SCHOOLS';
export const DELETE_SCHOOL = 'DELETE_SCHOOL';
export const CREATE_SCHOOL = 'CREATE_SCHOOL';


export const LOAD_STUDENTS = 'LOAD_STUDENTS';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';